tipoasignacion_homepage:
    path:     /index
    defaults: { _controller: TipoasignacionBundle:Default:index }

tipo_asignacion_nuevo:
    path: /principal
    defaults: { _controller: TipoasignacionBundle:Default:principal }

tipo_asignacion_guardar:
    path: /guardar
    defaults: { _controller: TipoasignacionBundle:Default:procesar }

tipo_asignacion_modificar:
    path: /modificar
    defaults: { _controller: TipoasignacionBundle:Default:procesar }

tipo_asignacion_eliminar:
    path: /eliminar
    defaults: { _controller: TipoasignacionBundle:Default:procesar }

tipo_asignacion_todos:
    path: /todotipoasignacion
    defaults: { _controller: TipoasignacionBundle:Default:todotipoasignacion }

