# prefix:   /master

areas_homepage:
    path:     /
    defaults: { _controller: MaestrasBundle:Areas:index } 

areas_nuevo:
   path: /principal
   defaults: { _controller: MaestrasBundle:Areas:principal }
    
areas_guardar:
   path: /guardar
   defaults: { _controller: MaestrasBundle:Areas:procesar }

areas_eliminar:
   path: /eliminar
   defaults: { _controller: MaestrasBundle:Areas:procesar }

areas_todos:
   path: /lista
   defaults: { _controller: MaestrasBundle:Areas:lista }

cargos_nuevo:
   path: /cp
   defaults: { _controller: MaestrasBundle:Cargos:principal }

cargos_guardar:
   path: /guardar_cargo
   defaults: { _controller: MaestrasBundle:Cargos:procesar }

cargos_eliminar:
   path: /eliminar_cargo
   defaults: { _controller: MaestrasBundle:Cargos:procesar }

cargos_todos:
   path: /lista_cargo
   defaults: { _controller: MaestrasBundle:Cargos:lista }