# prefix:   /usuario

usuario_homepage:
    path:   /
    defaults: { _controller: UsuarioBundle:Default:index }

usuario_nuevo:
    path:   /usu_pri
    defaults: { _controller: UsuarioBundle:Default:index }
    
usuario_login:
    path:   /login
    defaults: {_controller: UsuarioBundle:Default:login }
    
usuario_login_check:
    path:   /login_check

usuario_logout:
    path:   /logout
